MODEL:
  WEIGHT: "catalog://ImageNetPretrained/DLA34"
  BACKBONE:
    CONV_BODY: "RESNET-34"
    DOWN_RATIO: 4
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
  USE_RIGHT_PROB_TRAIN: 0.0
  USE_COLOR_PROB_TRAIN: 0.0
DATASETS:
  DETECT_CLASSES: ("Car", "Cyclist", "Pedestrian")
  TRAIN: ("kitti_train",)
  TEST: ("kitti_train",)
  TRAIN_SPLIT: "train"
  TEST_SPLIT: "val"
SOLVER:
  BASE_LR: 2.5e-4
  STEPS: (10000, 18000)
  MAX_ITERATION: 25000
  IMS_PER_BATCH: 8
  EVALUATE_PERIOD: 1000
OUTPUT_DIR: "/data-input/checkpoints/RESNET34_WEIGHTED_LOSS_2_Pc_PLUS_1_Pr_USE_RIGHT_CAMERA_004nd"
